export const vacancy = [
  {
    "id": 1,
    "company": "Apple",
    "direction": "Web-дизайнер(UI-UX)",
    "job": "Web-дизайнер(UI-UX)",
    "cost": "$2500-$4000",
    "country": "ОАЭ, Дубаи",
    "experience": "1-3 года",
    "format": "Полная занятость",
  },
  {
    "id": 2,
    "company": "Apple",
    "direction": "Бэкенд разработчик",
    "job": "Бэкенд разработчик",
    "cost": "$4500-$8000",
    "country": "ОАЭ, Дубаи",
    "experience": "1-3 года",
    "format": "30 часов",
  },
  {
    "id": 3,
    "company": "Apple",
    "direction": "Бэкенд разработчик",
    "job": "Бэкенд разработчик",
    "cost": "$2500-$4000",
    "country": "ОАЭ, Дубаи",
    "experience": "1-3 года",
    "format": "Работа в Офисе",
  },
  {
    "id": 4,
    "company": "Apple",
    "direction": "Бэкенд разработчик",
    "job": "Бэкенд разработчик",
    "cost": "$2500-$4000",
    "country": "ОАЭ, Дубаи",
    "experience": "1-3 года",
    "format": "Полная занятость",
  }
]